### ISSUE TITLE
mysql connection forcibly closes and kills process

### ISSUE THREAD

**Issue by pacjman** [pacjman/blog-wordpress-api#1]
```src/github/pacjman$ sudo docker logs bbe```

> blog-wordpress-api@1.0.0 start /usr/src/app
> node -r dotenv/config dist/index.js

```events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:97:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:502:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blog-wordpress-api@1.0.0 start: `node -r dotenv/config dist/index.js`
npm ERR! Exit status 1```

**Comment by pacjman** [comment]
issue fixed in rev 6efe97f
